# Generated by Django 5.0.7 on 2024-07-21 11:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=200)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('model_year', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
                ('msrp', models.IntegerField()),
                ('dealer_discounts', models.IntegerField()),
                ('vehicle_overview', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('date_added', models.DateField(editable=False)),
                ('date_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vehicle_photos/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainapp.vehicle')),
            ],
        ),
    ]
